backend:
  name: github
  repo: matrooshkaa/haiku
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "نوشته‌ها"
    folder: "_posts"
    create: true
    fields:
      - {label: "عنوان", name: "title", widget: "string"}
      - {label: "متن", name: "body", widget: "markdown"}
